services:
  - type: web
    name: quicknote-api
    runtime: image
    repo: https://github.com/JosePablo1996/QuickNote-Api_APP_React-
    branch: master
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: ENVIRONMENT
        value: production