services:
  # Servicio web para la API FastAPI
  - type: web
    name: quicknote-api
    runtime: python
    repo: https://github.com/JosePablo1996/QuickNote-Api_APP_React-
    branch: master
    buildCommand: |
      echo "Usando Python 3.12"
      python3.12 -m pip install --upgrade pip
      python3.12 -m pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: PYTHON_VERSION
        value: 3.12.10